USE DATABASE BRIGHTCOFFEESHOP;

SELECT  * FROM BRIGHTCOFFEESHOP.BRIGHTCOFFEESHOP_SCH.BRIGHT_TBL;

SELECT  (DISTINCT PRODUCT_CATEGORY),PRODUCT_TYPE
FROM BRIGHTCOFFEESHOP.BRIGHTCOFFEESHOP_SCH.BRIGHT_TBL;

SELECT DISTINCT 

SELECT DISTINCT PRODUCT_CATEGORY
FROM BRIGHTCOFFEESHOP.BRIGHTCOFFEESHOP_SCH.BRIGHT_TBL;

SELECT DISTINCT Product_category
FROM BRIGHTCOFFEESHOP.BRIGHTCOFFEESHOP_SCH.BRIGHT_TBL;

SELECT DISTINCT PRODUCT_ID
FROM BRIGHTCOFFEESHOP.BRIGHTCOFFEESHOP_SCH.BRIGHT_TBL;

SELECT TO_CHAR(TRANSACTION_DATE, 'MON') AS Month_Name
FROM BRIGHTCOFFEESHOP.BRIGHTCOFFEESHOP_SCH.BRIGHT_TBL;

SELECT MIN (TRANSACTION_TIME)
FROM BRIGHTCOFFEESHOP.BRIGHTCOFFEESHOP_SCH.BRIGHT_TBL;

SELECT PRODUCT_DETAIL,TRANSACTION_DATE,STORE_LOCATION,PRODUCT_CATEGORY,PRODUCT_TYPE,COUNT(DISTINCT TRANSACTION_ID) AS Number_of_Sales,
    SUM (UNIT_PRICE*TRANSACTION_QTY) AS TOTAL_REVENUE, STORE_ID,
          CASE
            WHEN TRANSACTION_TIME BETWEEN '06:00:00' AND '08:59:59' THEN 'MORNING'
            WHEN TRANSACTION_TIME BETWEEN '09:00:00' AND '11:59:59' THEN 'LATE MORNING'
            WHEN TRANSACTION_TIME BETWEEN '12:00:00' AND '16:59:59' THEN 'AFTERNOON'
            WHEN TRANSACTION_TIME BETWEEN '17:00:00' AND '18:59:59' THEN 'EVENING'
            ELSE 'DUSK'
                END AS TIME_CATEGORY,
            HOUR(TRANSACTION_TIME) AS Hour_of_day,
            DAYNAME(TRANSACTION_DATE) AS DAY_NAME,
            DATEADD(MONTH, -1, TRANSACTION_DATE) AS Previous_Month,
             TO_CHAR(TRANSACTION_DATE, 'MON, YYYY') AS Month_Name,
     CASE
        WHEN DAY_NAME IN ('Sun','Sat') THEN 'WEEKEND'
        ELSE 'WEEKDAYS'
        END Day_Classification,
         
FROM BRIGHTCOFFEESHOP.BRIGHTCOFFEESHOP_SCH.BRIGHT_TBL
GROUP BY ALL;

SELECT STORE_LOCATION,
 DAYNAME(TRANSACTION_DATE) AS DAY_NAME,
    CASE
        WHEN DAY_NAME IN ('Sun','Sat') THEN 'WEEKEND'
        ELSE 'WEEKDAYS'
        END Day_Classification
FROM BRIGHTCOFFEESHOP.BRIGHTCOFFEESHOP_SCH.BRIGHT_TBL;

SELECT 
    CAST(SUM(UNIT_PRICE * TRANSACTION_QTY) AS NUMBER(10,2)) AS REVENUE
FROM BRIGHTCOFFEESHOP.BRIGHTCOFFEESHOP_SCH.BRIGHT_TBL;

SELECT DATEADD(MONTH, -1, TRANSACTION_DATE) AS Previous_Month
FROM  BRIGHTCOFFEESHOP.BRIGHTCOFFEESHOP_SCH.BRIGHT_TBL;
